### ISSUE TITLE
Missing TPM.dev community attribution

### ISSUE THREAD

**Issue by tomoveu** [arlotito/iotedge-tpm2cloud#1]
Hi Arturo,

I am happy that you succeeded in your quest to produce this tutorial. However, you openly discussed this in the all-members chat of TPM.dev, and our community provided you with information. We also had a separate call exclusively on this topic to answer all your questions.

Our TPM.dev community exists on a voluntary basis and is open to everyone. By providing attribution you express your respect and appreciation of the work of our community members and help new members join the community for the benefit of all developers.

Please add the following attribution in your tutorial:

```
* [TPM.dev Developer's Community](https://tpm.dev/)
```

**Comment by arlotito** [comment]
Hi, I'm not sure what should be attributed to your community. The tutorial?

We had a chat + call around a single and specific issue: access to the TPM's platform hierarchy using the tpm2_tools from the OS. Despite the inspiring conversation, we didn't identify the root-cause at that time (and later-on I figured out on my own it was due to a different behavior of the ibm sw tpm vs swtpm).

However, this tutorial is much broader than that single specific issue, isn't it?

I do respect and appreciate knowledgeable and skilled people helping each other, in a truly open way, without any commercial intent or affiliation. Assuming this is the spirit of your devs open community, your attribution request sounds a bit weird.
